-- CreateTable
CREATE TABLE "User" ("id" TEXT NOT NULL,"googleId" TEXT NOT NULL,"email" TEXT NOT NULL,"name" TEXT NOT NULL,"avatarUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuthSession" ("id" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"userId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuthSession_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Site" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"domain" TEXT NOT NULL,"siteKey" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Site_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Visitor" ("id" TEXT NOT NULL,"siteId" TEXT NOT NULL,"visitorIdHash" TEXT NOT NULL,"firstSeenAt" TIMESTAMP(3) NOT NULL,"lastSeenAt" TIMESTAMP(3) NOT NULL,"visitCount" INTEGER NOT NULL DEFAULT 1,"firstIpHash" TEXT,"lastIpHash" TEXT,"userAgentHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Visitor_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL,"siteId" TEXT NOT NULL,"visitorIdHash" TEXT NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL,"lastActivityAt" TIMESTAMP(3) NOT NULL,"endedAt" TIMESTAMP(3),"pageCount" INTEGER NOT NULL DEFAULT 0,"entryPath" TEXT,"exitPath" TEXT,"referrer" TEXT,"source" TEXT,"medium" TEXT,"campaign" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PageView" ("id" TEXT NOT NULL,"eventId" TEXT NOT NULL,"siteId" TEXT NOT NULL,"visitorIdHash" TEXT NOT NULL,"sessionId" TEXT NOT NULL,"path" TEXT NOT NULL,"fullUrl" TEXT,"referrer" TEXT,"source" TEXT,"medium" TEXT,"campaign" TEXT,"deviceType" TEXT NOT NULL,"browser" TEXT,"browserVersion" TEXT,"os" TEXT,"osVersion" TEXT,"language" TEXT,"timezone" TEXT,"screenWidth" INTEGER,"screenHeight" INTEGER,"country" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PageView_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Event" ("id" TEXT NOT NULL,"eventId" TEXT NOT NULL,"siteId" TEXT NOT NULL,"visitorIdHash" TEXT NOT NULL,"sessionId" TEXT,"name" TEXT NOT NULL,"properties" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Event_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_googleId_key" ON "User"("googleId"); CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "AuthSession_tokenHash_key" ON "AuthSession"("tokenHash"); CREATE UNIQUE INDEX "Site_siteKey_key" ON "Site"("siteKey"); CREATE UNIQUE INDEX "Visitor_siteId_visitorIdHash_key" ON "Visitor"("siteId","visitorIdHash"); CREATE UNIQUE INDEX "PageView_siteId_eventId_key" ON "PageView"("siteId","eventId"); CREATE UNIQUE INDEX "Event_siteId_eventId_key" ON "Event"("siteId","eventId");
CREATE INDEX "User_email_idx" ON "User"("email"); CREATE INDEX "AuthSession_userId_idx" ON "AuthSession"("userId"); CREATE INDEX "AuthSession_expiresAt_idx" ON "AuthSession"("expiresAt"); CREATE INDEX "Site_userId_idx" ON "Site"("userId"); CREATE INDEX "Site_domain_idx" ON "Site"("domain"); CREATE INDEX "Visitor_siteId_idx" ON "Visitor"("siteId"); CREATE INDEX "Visitor_siteId_lastSeenAt_idx" ON "Visitor"("siteId","lastSeenAt"); CREATE INDEX "Session_siteId_startedAt_idx" ON "Session"("siteId","startedAt"); CREATE INDEX "Session_visitorIdHash_idx" ON "Session"("visitorIdHash"); CREATE INDEX "PageView_siteId_createdAt_idx" ON "PageView"("siteId","createdAt"); CREATE INDEX "PageView_siteId_path_idx" ON "PageView"("siteId","path"); CREATE INDEX "PageView_visitorIdHash_idx" ON "PageView"("visitorIdHash"); CREATE INDEX "PageView_sessionId_idx" ON "PageView"("sessionId"); CREATE INDEX "Event_siteId_createdAt_idx" ON "Event"("siteId","createdAt");
ALTER TABLE "AuthSession" ADD CONSTRAINT "AuthSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Site" ADD CONSTRAINT "Site_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Visitor" ADD CONSTRAINT "Visitor_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Session" ADD CONSTRAINT "Session_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "PageView" ADD CONSTRAINT "PageView_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "PageView" ADD CONSTRAINT "PageView_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Event" ADD CONSTRAINT "Event_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Event" ADD CONSTRAINT "Event_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session"("id") ON DELETE SET NULL ON UPDATE CASCADE;
