import { Elysia, t } from "elysia";
import cors from "@elysiajs/cors";
import { createHash, randomUUID } from "node:crypto";
import { createRemoteJWKSet, jwtVerify } from "jose";
import { prisma } from "./db/prisma";
import { redis } from "./redis/redis";
import { touchPresence, activeCount } from "./redis/presence";
import { rateLimit } from "./redis/rate-limit";
import { config } from "./config/config";
import { clientIp } from "./utils/ip";
import { domainOk, normalizeDomain } from "./utils/domain";
import { hash, newKey } from "./utils/hashing";
import { parseUserAgent } from "./utils/user-agent";
import { apiError } from "./utils/errors";
import { logger } from "./utils/logger";
import { requestId } from "./middleware/request-context";
import { securityHeaders } from "./middleware/security";
import { getPublicVisitorCount } from "./services/public-stats.service";

const error = apiError;
const tokenHash=(token:string)=>createHash("sha256").update(token+config.sessionSecret).digest("hex");
const googleKeys=createRemoteJWKSet(new URL("https://www.googleapis.com/oauth2/v3/certs"));
const oauthStateHash=(state:string)=>createHash("sha256").update(state+config.sessionSecret).digest("hex");
async function currentUser(request:Request){const raw=request.headers.get("cookie")?.match(/analytics_session=([^;]+)/)?.[1];if(!raw)return null;const s=await prisma.authSession.findUnique({where:{tokenHash:tokenHash(raw)},include:{user:true}});return s&&s.expiresAt>new Date()?s.user:null;}
type SiteAccess = {ok:true;site:NonNullable<Awaited<ReturnType<typeof prisma.site.findUnique>>>}|{ok:false;error:ReturnType<typeof error>};
async function siteFor(request:Request,key:string):Promise<SiteAccess>{const user=await currentUser(request);if(!user)return {ok:false,error:error("UNAUTHENTICATED","Authentication required",401)};const site=await prisma.site.findUnique({where:{siteKey:key}});if(!site)return {ok:false,error:error("NOT_FOUND","Site not found",404)};if(site.userId!==user.id)return {ok:false,error:error("FORBIDDEN","You do not own this site",403)};return {ok:true,site};}
function source(ref:string|null,u:{source?:string|null}){if(u.source)return u.source.toLowerCase();if(!ref)return "direct";try{const h=new URL(ref).hostname.replace(/^www\./,"");if(h.includes("google"))return "google";if(h.includes("youtube"))return "youtube";if(h.includes("discord"))return "discord";if(h.includes("telegram"))return "telegram";if(h.includes("twitter")||h.includes("x.com"))return "twitter";if(h.includes("instagram"))return "instagram";return "referral";}catch{return "referral";}}
const tracking=t.Object({siteKey:t.String({minLength:5,maxLength:100}),visitorId:t.String({minLength:10,maxLength:100}),eventId:t.Optional(t.String({maxLength:100})),path:t.String({minLength:1,maxLength:2000}),fullUrl:t.Optional(t.String({maxLength:4000})),referrer:t.Optional(t.Union([t.String({maxLength:4000}),t.Null()])),language:t.Optional(t.String({maxLength:50})),timezone:t.Optional(t.String({maxLength:100})),screenWidth:t.Optional(t.Integer({minimum:0,maximum:10000})),screenHeight:t.Optional(t.Integer({minimum:0,maximum:10000})),userAgent:t.Optional(t.String({maxLength:1000})),utm:t.Optional(t.Object({source:t.Optional(t.Union([t.String({maxLength:200}),t.Null()])),medium:t.Optional(t.Union([t.String({maxLength:200}),t.Null()])),campaign:t.Optional(t.Union([t.String({maxLength:200}),t.Null()]))}))});
const app=new Elysia().use(cors({origin:(request)=>{const path=new URL(request.url).pathname;return path.startsWith("/api/v1/public/")||path.includes("/api/v1/track")||path.includes("/api/v1/events")||config.corsOrigins.includes(request.headers.get("origin")??"");},credentials:true})).onBeforeHandle(async({request,set,server})=>{if(request.method!=="OPTIONS"){const path=new URL(request.url).pathname;if(path!=="/health"&&path!=="/ready"&&path!=="/script.js"){const isPublicStats=path.startsWith("/api/v1/public/sites/");const max=isPublicStats?config.publicStatsRateMax:path.startsWith("/api/v1/auth")?config.authRateMax:path.startsWith("/api/v1/stats")||path.startsWith("/api/v1/sites")?config.dashboardRateMax:config.rateMax;const windowSeconds=isPublicStats?config.publicStatsRateWindow:config.rateWindow;if(!await rateLimit(clientIp(request,server),max,windowSeconds)){set.status=429;return error("RATE_LIMITED","Too many requests",429);}}}}).onError(({code,error:err,set})=>{console.error(JSON.stringify({code,message:err instanceof Error?err.message:"request error"}));set.status=code==="VALIDATION"?400:500;return error(code==="VALIDATION"?"INVALID_REQUEST":"INTERNAL_ERROR",code==="VALIDATION"?"Invalid request":config.nodeEnv==="production"?"Internal server error":err instanceof Error?err.message:"Internal server error",set.status as number);});
app.onRequest(({ request, set }) => {
  set.headers["x-request-id"] = requestId(request);
});
app.onAfterHandle(({ request, set }) => {
  Object.assign(set.headers, securityHeaders, { "x-request-id": requestId(request) });
  if (new URL(request.url).pathname !== "/script.js" && !set.headers["cache-control"]) set.headers["cache-control"] = "no-store";
  logger.info("http.request", { route: new URL(request.url).pathname, status: set.status ?? 200, requestId: requestId(request) });
});
app.get("/health",()=>({ok:true,status:"alive"}));
app.get("/ready",async({set})=>{try{await prisma.$queryRaw`SELECT 1`;await redis.ping();return {ok:true,status:"ready"};}catch{set.status=503;return error("NOT_READY","Dependencies unavailable",503);}});
app.get("/script.js",()=>new Response(Bun.file("tracking/script.js"),{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"public,max-age=300"}}));

app.get("/api/v1/auth/google",({set})=>{if(!config.googleClientId){set.status=503;return error("AUTH_NOT_CONFIGURED","Google authentication is not configured",503);}const state=randomUUID()+randomUUID(),u=new URL("https://accounts.google.com/o/oauth2/v2/auth");u.searchParams.set("client_id",config.googleClientId);u.searchParams.set("redirect_uri",config.googleRedirectUri);u.searchParams.set("response_type","code");u.searchParams.set("scope","openid email profile");u.searchParams.set("state",state);set.status=302;set.headers={location:u.toString(),"set-cookie":`oauth_state=${oauthStateHash(state)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=600${config.nodeEnv==="production"?"; Secure":""}`};});
app.get("/api/v1/auth/google/callback",async({query,request,set})=>{const stateCookie=request.headers.get("cookie")?.match(/(?:^|; )oauth_state=([^;]+)/)?.[1];if(!query.code||!query.state||!stateCookie||stateCookie!==oauthStateHash(query.state)){set.status=400;return error("INVALID_OAUTH_STATE","Invalid OAuth state");}const body=new URLSearchParams({code:query.code,client_id:config.googleClientId,client_secret:Bun.env.GOOGLE_CLIENT_SECRET??"",redirect_uri:config.googleRedirectUri,grant_type:"authorization_code"});const tok=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}).then(r=>r.json()) as {id_token?:string};if(!tok.id_token){set.status=401;return error("AUTH_FAILED","Google authentication failed",401);}let c;try{c=(await jwtVerify(tok.id_token,googleKeys,{issuer:["https://accounts.google.com","accounts.google.com"],audience:config.googleClientId})).payload;}catch{set.status=401;return error("AUTH_FAILED","Invalid Google identity",401);}if(typeof c.sub!=="string"||typeof c.email!=="string"){set.status=401;return error("AUTH_FAILED","Invalid Google identity",401);}const u=await prisma.user.upsert({where:{googleId:c.sub},create:{googleId:c.sub,email:c.email,name:typeof c.name==="string"?c.name:c.email,avatarUrl:typeof c.picture==="string"?c.picture:null},update:{email:c.email,name:typeof c.name==="string"?c.name:c.email,avatarUrl:typeof c.picture==="string"?c.picture:null}});const raw=randomUUID()+randomUUID();await prisma.authSession.create({data:{tokenHash:tokenHash(raw),userId:u.id,expiresAt:new Date(Date.now()+config.sessionTtl*1000)}});set.status=302;set.headers={"set-cookie":`analytics_session=${raw}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${config.sessionTtl}${config.nodeEnv==="production"?"; Secure":""}`,location:"/"};});
app.post("/api/v1/auth/logout",async({request,set})=>{const raw=request.headers.get("cookie")?.match(/analytics_session=([^;]+)/)?.[1];if(raw)await prisma.authSession.deleteMany({where:{tokenHash:tokenHash(raw)}});set.headers={"set-cookie":"analytics_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0"};return {ok:true};});
app.get("/api/v1/auth/me",async({request,set})=>{const u=await currentUser(request);if(!u){set.status=401;return error("UNAUTHENTICATED","Authentication required",401);}return {id:u.id,email:u.email,name:u.name,avatarUrl:u.avatarUrl};});

app.post("/api/v1/sites",async({request,body,set})=>{const u=await currentUser(request);if(!u){set.status=401;return error("UNAUTHENTICATED","Authentication required",401);}if(!domainOk(body.domain)){set.status=400;return error("INVALID_DOMAIN","Invalid domain");}set.status=201;return prisma.site.create({data:{userId:u.id,name:body.name.trim(),domain:normalizeDomain(body.domain),siteKey:newKey()}});},{body:t.Object({name:t.String({minLength:1,maxLength:120}),domain:t.String({minLength:3,maxLength:255})})});
app.get("/api/v1/sites",async({request,set})=>{const u=await currentUser(request);if(!u){set.status=401;return error("UNAUTHENTICATED","Authentication required",401);}return prisma.site.findMany({where:{userId:u.id},orderBy:{createdAt:"desc"}});});
app.get("/api/v1/sites/:id",async({request,params,set})=>{const u=await currentUser(request),s=await prisma.site.findUnique({where:{id:params.id}});if(!u){set.status=401;return error("UNAUTHENTICATED","Authentication required",401);}if(!s){set.status=404;return error("NOT_FOUND","Site not found",404);}if(s.userId!==u.id){set.status=403;return error("FORBIDDEN","You do not own this site",403);}return s;});
app.patch("/api/v1/sites/:id",async({request,params,body,set})=>{const u=await currentUser(request),s=await prisma.site.findUnique({where:{id:params.id}});if(!u){set.status=401;return error("UNAUTHENTICATED","Authentication required",401);}if(!s){set.status=404;return error("NOT_FOUND","Site not found",404);}if(s.userId!==u.id){set.status=403;return error("FORBIDDEN","You do not own this site",403);}if(body.domain&&!domainOk(body.domain)){set.status=400;return error("INVALID_DOMAIN","Invalid domain");}return prisma.site.update({where:{id:s.id},data:{name:body.name?.trim(),domain:body.domain?normalizeDomain(body.domain):undefined}});},{body:t.Object({name:t.Optional(t.String({minLength:1,maxLength:120})),domain:t.Optional(t.String({minLength:3,maxLength:255}))})});
app.delete("/api/v1/sites/:id",async({request,params,set})=>{const u=await currentUser(request),s=await prisma.site.findUnique({where:{id:params.id}});if(!u){set.status=401;return error("UNAUTHENTICATED","Authentication required",401);}if(!s){set.status=404;return error("NOT_FOUND","Site not found",404);}if(s.userId!==u.id){set.status=403;return error("FORBIDDEN","You do not own this site",403);}await prisma.site.delete({where:{id:s.id}});return {ok:true};});

app.post("/api/v1/track",async({body,request})=>{const site=await prisma.site.findUnique({where:{siteKey:body.siteKey}});if(!site)return error("INVALID_SITE_KEY","Invalid site key");const vh=hash(body.visitorId),now=new Date(),ua=request.headers.get("user-agent")??"",p=parseUserAgent(ua),ip=hash(clientIp(request)),ref=body.referrer??null,utm=body.utm??{},src=source(ref,utm),old=await prisma.visitor.findUnique({where:{siteId_visitorIdHash:{siteId:site.id,visitorIdHash:vh}}});await prisma.visitor.upsert({where:{siteId_visitorIdHash:{siteId:site.id,visitorIdHash:vh}},create:{siteId:site.id,visitorIdHash:vh,firstSeenAt:now,lastSeenAt:now,firstIpHash:ip,lastIpHash:ip,userAgentHash:hash(ua)},update:{lastSeenAt:now,lastIpHash:ip}});let session=await prisma.session.findFirst({where:{siteId:site.id,visitorIdHash:vh,lastActivityAt:{gte:new Date(now.getTime()-config.sessionTimeoutMs)},endedAt:null},orderBy:{lastActivityAt:"desc"}});if(!session){session=await prisma.session.create({data:{siteId:site.id,visitorIdHash:vh,startedAt:now,lastActivityAt:now,entryPath:body.path,referrer:ref,source:src,medium:utm.medium??null,campaign:utm.campaign??null}});if(old)await prisma.visitor.update({where:{siteId_visitorIdHash:{siteId:site.id,visitorIdHash:vh}},data:{visitCount:{increment:1}}});}try{await prisma.$transaction([prisma.pageView.create({data:{eventId:body.eventId??randomUUID(),siteId:site.id,visitorIdHash:vh,sessionId:session.id,path:body.path,fullUrl:body.fullUrl??null,referrer:ref,source:src,medium:utm.medium??null,campaign:utm.campaign??null,...p,language:body.language??null,timezone:body.timezone??null,screenWidth:body.screenWidth??null,screenHeight:body.screenHeight??null}}),prisma.session.update({where:{id:session.id},data:{lastActivityAt:now,pageCount:{increment:1},exitPath:body.path}})]);}catch(e){if(!(e instanceof Error)||!e.message.includes("Unique constraint"))throw e;}await touchPresence(site.id,vh);return {ok:true};},{body:tracking});
const eventBody=t.Object({siteKey:t.String({minLength:5,maxLength:100}),visitorId:t.String({minLength:10,maxLength:100}),name:t.String({minLength:1,maxLength:100,pattern:"^[A-Za-z0-9_.:-]+$"}),properties:t.Optional(t.Record(t.String({maxLength:50}),t.Union([t.String({maxLength:500}),t.Number(),t.Boolean(),t.Null()]),{maxProperties:20})) });
app.post("/api/v1/events",async({body,request,set})=>{const site=await prisma.site.findUnique({where:{siteKey:body.siteKey}});if(!site){set.status=400;return error("INVALID_SITE_KEY","Invalid site key");}const visitorIdHash=hash(body.visitorId),session=await prisma.session.findFirst({where:{siteId:site.id,visitorIdHash,endedAt:null,lastActivityAt:{gte:new Date(Date.now()-config.sessionTimeoutMs)}},orderBy:{lastActivityAt:"desc"}});await prisma.event.create({data:{eventId:randomUUID(),siteId:site.id,visitorIdHash,sessionId:session?.id??null,name:body.name,properties:body.properties??{}}});await touchPresence(site.id,visitorIdHash);return {ok:true};},{body:eventBody});

app.get("/api/v1/public/sites/:siteKey/visitor-count",async({params,set})=>{const counts=await getPublicVisitorCount(params.siteKey);if(!counts){set.status=404;return error("SITE_NOT_FOUND","Site not found",404);}set.headers["cache-control"]="no-cache";return counts;},{params:t.Object({siteKey:t.String({minLength:5,maxLength:100})})});

app.get("/api/v1/stats",async({request,query,set})=>{const o=await siteFor(request,query.siteKey);if(!o.ok){set.status=o.error.error.status;return o.error;}const days=query.range==="30d"?30:query.range==="7d"?7:1,since=new Date(Date.now()-days*86400000),where={siteId:o.site.id,createdAt:{gte:since}},[views,uniqueRows,sessions,newVisitors,returningVisitors,active]=await Promise.all([prisma.pageView.count({where}),prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(DISTINCT "visitorIdHash")::bigint AS count FROM "PageView" WHERE "siteId"=${o.site.id} AND "createdAt">=${since}`,prisma.session.count({where:{siteId:o.site.id,startedAt:{gte:since}}}),prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(DISTINCT pv."visitorIdHash")::bigint AS count FROM "PageView" pv JOIN "Visitor" v ON v."siteId"=pv."siteId" AND v."visitorIdHash"=pv."visitorIdHash" WHERE pv."siteId"=${o.site.id} AND pv."createdAt">=${since} AND v."firstSeenAt">=${since}`,prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(DISTINCT pv."visitorIdHash")::bigint AS count FROM "PageView" pv JOIN "Visitor" v ON v."siteId"=pv."siteId" AND v."visitorIdHash"=pv."visitorIdHash" WHERE pv."siteId"=${o.site.id} AND pv."createdAt">=${since} AND v."firstSeenAt"<${since}`,activeCount(o.site.id)]);const uniqueVisitors=Number(uniqueRows[0]?.count??0),newCount=Number(newVisitors[0]?.count??0),returningCount=Number(returningVisitors[0]?.count??0);return {totalViews:views,uniqueVisitors,newVisitors:newCount,returningVisitors:returningCount,activeVisitors:active,sessions};},{query:t.Object({siteKey:t.String(),range:t.Optional(t.Union([t.Literal("24h"),t.Literal("7d"),t.Literal("30d")]))})});
app.get("/api/v1/stats/pages",async({request,query,set})=>{const o=await siteFor(request,query.siteKey);if(!o.ok){set.status=o.error.error.status;return o.error;}const days=query.range==="30d"?30:query.range==="7d"?7:1,since=new Date(Date.now()-days*86400000),rows=await prisma.$queryRaw<Array<{path:string;views:bigint;uniqueVisitors:bigint}>>`SELECT "path", COUNT(*)::bigint AS views, COUNT(DISTINCT "visitorIdHash")::bigint AS "uniqueVisitors" FROM "PageView" WHERE "siteId"=${o.site.id} AND "createdAt">=${since} GROUP BY "path" ORDER BY views DESC LIMIT 100`;return rows.map((row: { path: any; views: any; uniqueVisitors: any; })=>({path:row.path,views:Number(row.views),uniqueVisitors:Number(row.uniqueVisitors)}));},{query:t.Object({siteKey:t.String(),range:t.Optional(t.Union([t.Literal("24h"),t.Literal("7d"),t.Literal("30d")]))})});
app.ws("/ws/track",{maxPayloadLength:2048,open:ws=>ws.send(JSON.stringify({ok:true,heartbeatSeconds:15})),message:async(ws,message)=>{try{// Elysia auto-parses JSON frames — message may already be an object.
      const obj:Record<string,unknown>=typeof message==="string"?JSON.parse(message):message as Record<string,unknown>;
      if(typeof obj!=="object"||obj===null)return;
      const raw=JSON.stringify(obj);if(raw.length>500)return;
      const siteKey=obj["siteKey"],visitorId=obj["visitorId"];
      if(typeof siteKey!=="string"||siteKey.length<5||siteKey.length>100)return;
      if(typeof visitorId!=="string"||visitorId.length<10||visitorId.length>100)return;
      const s=await prisma.site.findUnique({where:{siteKey}});
      if(!s)return;
      await touchPresence(s.id,hash(visitorId));
      ws.send(JSON.stringify({ok:true,type:"presence_ack"}));}catch{}}});
app.get("/health", () => ({ ok: true }));
export { app };
